// <auto-generated />
using System;
using EmisTracking.Services.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmisTracking.Services.Database.Migrations.EmissionDb
{
    [DbContext(typeof(EmissionDbContext))]
    [Migration("20250511074542_InitialEdbCreate")]
    partial class InitialEdbCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmisTracking.Services.Entities.Area", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.Consumption", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ConsumptionGroupId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("Mass")
                        .HasColumnType("float");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsumptionGroupId");

                    b.ToTable("Consumptions");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.ConsumptionGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("MethodologyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConsumptionGroups");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.EmissionSource", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("MethodologyId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModeId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessCategory")
                        .HasColumnType("int");

                    b.Property<string>("SubdivisionId")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("MethodologyId");

                    b.HasIndex("ModeId");

                    b.HasIndex("SubdivisionId");

                    b.ToTable("EmissionSources");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.GrossEmission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("Mass")
                        .HasColumnType("float");

                    b.Property<string>("MethodologyId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("SourceSubstanceId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MethodologyId");

                    b.HasIndex("SourceSubstanceId");

                    b.HasIndex("TaxId");

                    b.ToTable("GrossEmissions");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.Methodology", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Formula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Methodologies");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.MethodologyParameter", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("MethodologyId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("ParameterType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MethodologyId");

                    b.ToTable("MethodologyParameters");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.Mode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessCategory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Modes");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.OperatingTime", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("EmissionSourceId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmissionSourceId");

                    b.ToTable("OperatingTimes");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.ParameterValue", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("GrossEmissionId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("MethodologyParameterId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrossEmissionId");

                    b.HasIndex("MethodologyParameterId");

                    b.ToTable("ParameterValues");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.Pollutant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("AggregateState")
                        .HasColumnType("int");

                    b.Property<int>("HazardClass")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pollutants");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.SourceSubstance", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("AnnualAmount")
                        .HasColumnType("float");

                    b.Property<string>("EmissionSourceId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("GasCleaningUnitType")
                        .HasColumnType("int");

                    b.Property<bool>("IsRegulated")
                        .HasColumnType("bit");

                    b.Property<string>("PollutantId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("PurificationPercentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EmissionSourceId");

                    b.HasIndex("PollutantId");

                    b.ToTable("SourceSubstances");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.SpecificIndicator", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ConsumptionGroupId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("PollutantId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ConsumptionGroupId");

                    b.HasIndex("PollutantId");

                    b.ToTable("SpecificIndicators");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.Subdivision", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("AreaId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Subdivisions");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.Tax", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("TaxRateId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaxRateId");

                    b.ToTable("Taxes");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.TaxRate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HazardClass")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TaxRates");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.Consumption", b =>
                {
                    b.HasOne("EmisTracking.Services.Entities.ConsumptionGroup", null)
                        .WithMany()
                        .HasForeignKey("ConsumptionGroupId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.EmissionSource", b =>
                {
                    b.HasOne("EmisTracking.Services.Entities.Methodology", null)
                        .WithMany()
                        .HasForeignKey("MethodologyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EmisTracking.Services.Entities.Mode", null)
                        .WithMany()
                        .HasForeignKey("ModeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EmisTracking.Services.Entities.Subdivision", null)
                        .WithMany()
                        .HasForeignKey("SubdivisionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.GrossEmission", b =>
                {
                    b.HasOne("EmisTracking.Services.Entities.Methodology", null)
                        .WithMany()
                        .HasForeignKey("MethodologyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EmisTracking.Services.Entities.SourceSubstance", null)
                        .WithMany()
                        .HasForeignKey("SourceSubstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EmisTracking.Services.Entities.Tax", null)
                        .WithMany()
                        .HasForeignKey("TaxId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.MethodologyParameter", b =>
                {
                    b.HasOne("EmisTracking.Services.Entities.Methodology", null)
                        .WithMany()
                        .HasForeignKey("MethodologyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.OperatingTime", b =>
                {
                    b.HasOne("EmisTracking.Services.Entities.EmissionSource", null)
                        .WithMany()
                        .HasForeignKey("EmissionSourceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.ParameterValue", b =>
                {
                    b.HasOne("EmisTracking.Services.Entities.GrossEmission", null)
                        .WithMany()
                        .HasForeignKey("GrossEmissionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EmisTracking.Services.Entities.MethodologyParameter", null)
                        .WithMany()
                        .HasForeignKey("MethodologyParameterId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.SourceSubstance", b =>
                {
                    b.HasOne("EmisTracking.Services.Entities.EmissionSource", null)
                        .WithMany()
                        .HasForeignKey("EmissionSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EmisTracking.Services.Entities.Pollutant", null)
                        .WithMany()
                        .HasForeignKey("PollutantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.SpecificIndicator", b =>
                {
                    b.HasOne("EmisTracking.Services.Entities.ConsumptionGroup", null)
                        .WithMany()
                        .HasForeignKey("ConsumptionGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EmisTracking.Services.Entities.Pollutant", null)
                        .WithMany()
                        .HasForeignKey("PollutantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.Subdivision", b =>
                {
                    b.HasOne("EmisTracking.Services.Entities.Area", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EmisTracking.Services.Entities.Tax", b =>
                {
                    b.HasOne("EmisTracking.Services.Entities.TaxRate", null)
                        .WithMany()
                        .HasForeignKey("TaxRateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
